runtime: go116
main: app/_cmd

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75
  max_instances: 2
  min_instances: 0
  max_idle_instances: automatic
  min_idle_instances: 0
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 20

