runtime: go
api_version: go1

handlers:
  - url: /file/.*
    script: _go_app
  - url: /file_cache/.*
    script: _go_app
  - url: /page/.*
    script: _go_app
  - url: /(.*\.(gif|png|jpg|css|js|ico|xml))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js|ico|xml)$
  - url: /cache/(.*\.(gif|png|jpg|css|js|ico|xml))$
    static_files: public/\1
    expiration: "1d"
    upload: public/.*\.(gif|png|jpg|css|js|ico|xml)$
  - url: /manage/.*
    script: _go_app
    login: admin
    secure: always
  - url: /.*
    script: _go_app

