runtime: go116
main: app/_cmd

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.90
  target_throughput_utilization: 0.90
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 2
  min_pending_latency: 4000ms
  max_pending_latency: automatic
  max_concurrent_requests: 60

